name: Pruebas de Regresión - Cupones
  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Instalar dependencias
        run: |
          echo "Directorio actual:"
          pwd
          
          echo "Contenido del directorio antes de venv:"
          ls -la
          
          python -m venv venv
          
          echo "Contenido del directorio DESPUÉS de venv:"
          ls -la
          
          echo "Contenido de la carpeta venv/bin:"
          ls -la venv/bin
          python -m venv venv
          venv/bin/python -m pip install --upgrade pip
          venv/bin/pip install -r requirements.txt
          
      - name: Ejecutar pruebas
        run: |
          venv/bin/pytest
